import React, { useEffect, useMemo, useRef, useState } from "react";
import { useLocation } from "react-router-dom";
import api from "../../../api/api";
import { toast } from "react-toastify";

export default function TeacherSalaryRecord() {
  const [teachers, setTeachers] = useState([]);
  const [records, setRecords] = useState([]);
  const [selected, setSelected] = useState(null);
  const [processingId, setProcessingId] = useState(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [search, setSearch] = useState("");
  const [month, setMonth] = useState(() => {
    const d = new Date();
    return d.toLocaleString("en-US", { month: "long" }) + " " + d.getFullYear();
  });
  const location = useLocation();
  const initialTeacherId = location?.state?.teacherId || null;
  const autoGeneratedRef = useRef(false);
  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];
  const monthOptions = useMemo(() => {
    const currentYear = new Date().getFullYear();
    const years = [2025, currentYear];
    const uniqueYears = Array.from(new Set(years));
    return uniqueYears.flatMap((y) => months.map((m) => `${m} ${y}`));
  }, []);

  useEffect(() => {
    loadTeachers();
  }, []);

  useEffect(() => {
    loadRecords();
  }, [month]);

  const loadTeachers = async () => {
    try {
      const res = await api.get("/api/teacher-salary/teachers");
      setTeachers(res.data || []);
    } catch (err) {
      console.error("Error loading teachers:", err);
      toast.error("Failed to load teachers.");
    }
  };

  useEffect(() => {
    if (!initialTeacherId || teachers.length === 0) return;
    const found = teachers.find((t) => String(t._id) === String(initialTeacherId));
    if (found) setSelected(found);
  }, [initialTeacherId, teachers]);

  const loadRecords = async () => {
    try {
      setLoading(true);
      const res = await api.get("/api/teacher-salary/all");
      setRecords(res.data || []);
    } catch (err) {
      console.error("Error loading salary records:", err);
      toast.error("Failed to load salary records.");
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateSheet = async () => {
    if (!month) return;
    setGenerating(true);
    try {
      await api.post("/api/teacher-salary/monthly-sheet", { month });
      toast.success("Monthly sheet generated.");
      await loadRecords();
    } catch (err) {
      console.error("Error generating sheet:", err);
      toast.error("Failed to generate monthly sheet.");
    } finally {
      setGenerating(false);
    }
  };

  const handlePayNow = async (salaryId) => {
    if (!salaryId) return;
    setProcessingId(salaryId);
    try {
      await api.post(`/api/teacher-salary/payout/${salaryId}`);
      await loadRecords();
      toast.success("Payout processed.");
    } catch (err) {
      console.error("Error initiating payout:", err);
      toast.error("Failed to process payout.");
    } finally {
      setProcessingId(null);
    }
  };

  const handlePayWithRazorpay = async (record) => {
    if (!record?._id) return;
    if (!window.Razorpay) {
      toast.error("Razorpay SDK not loaded.");
      return;
    }
    setProcessingId(record._id);
    try {
      const res = await api.post(`/api/teacher-salary/razorpay/order/${record._id}`);
      if (res.data?.salary?.payoutStatus === "Paid") {
        toast.info("Payout already completed.");
        return;
      }

      const order = res.data?.order;
      const keyId = res.data?.keyId;
      if (!order?.id || !keyId) {
        toast.error("Failed to create Razorpay order.");
        return;
      }

      const options = {
        key: keyId,
        amount: order.amount,
        currency: order.currency,
        name: "SchoolY",
        description: `Salary payout - ${record.month}`,
        order_id: order.id,
        handler: async (response) => {
          try {
            await api.post("/api/teacher-salary/razorpay/verify", {
              salaryId: record._id,
              ...response,
            });
            toast.success("Payment successful.");
            await loadRecords();
          } catch (verifyErr) {
            console.error("Error verifying payment:", verifyErr);
            toast.error("Payment verification failed.");
          } finally {
            setProcessingId(null);
          }
        },
        modal: {
          ondismiss: () => {
            toast.info("Payment cancelled.");
            setProcessingId(null);
          },
        },
        prefill: {
          name: record.teacher?.teacherName || "Teacher",
          email: record.teacher?.email || "",
        },
        notes: {
          salaryId: record._id,
          month: record.month,
        },
        theme: { color: "#0d6efd" },
      };

      const rzp = new window.Razorpay(options);
      rzp.on("payment.failed", (resp) => {
        console.error("Razorpay payment failed:", resp);
        toast.error(resp?.error?.description || "Payment failed.");
        setProcessingId(null);
      });
      rzp.open();
    } catch (err) {
      console.error("Error creating Razorpay order:", err);
      toast.error("Failed to initiate Razorpay payment.");
      setProcessingId(null);
    }
  };


  const handleCreateRecord = async (teacher) => {
    try {
      const payload = {
        teacher: teacher._id,
        month,
        paidAmount: teacher.salary || 0,
        status: "Pending",
      };
      const res = await api.post("/api/teacher-salary/pay", payload);
      toast.success("Salary record created.");
      await loadRecords();
      return res.data?.salary || null;
    } catch (err) {
      if (err?.response?.status === 409) {
        toast.info("Salary record already exists.");
        await loadRecords();
        return err?.response?.data?.record || null;
      }
      console.error("Error creating salary record:", err);
      toast.error("Failed to create salary record.");
      return null;
    }
  };


  const recordByTeacher = useMemo(() => {
    const map = new Map();
    (records || [])
      .filter((r) => r?.month === month)
      .forEach((r) => {
        if (r?.teacher?._id) map.set(String(r.teacher._id), r);
      });
    return map;
  }, [records, month]);

  const monthlyRecordCount = useMemo(() => {
    return (records || []).filter((r) => r?.month === month).length;
  }, [records, month]);

  const isMonthlyGenerated = useMemo(() => {
    if (!teachers.length) return false;
    return monthlyRecordCount >= teachers.length;
  }, [monthlyRecordCount, teachers.length]);

  const filteredTeachers = useMemo(() => {
    const q = search.trim().toLowerCase();
    return (teachers || []).filter((t) => {
      if (!q) return true;
      const name = (t?.teacherName || "").toLowerCase();
      const email = (t?.email || "").toLowerCase();
      return name.includes(q) || email.includes(q);
    });
  }, [teachers, search]);

  useEffect(() => {
    if (autoGeneratedRef.current) return;
    if (loading) return;
    if (!teachers.length) return;
    if (isMonthlyGenerated) return;
    autoGeneratedRef.current = true;
    handleGenerateSheet();
  }, [loading, teachers.length, isMonthlyGenerated]);

  const selectedRecord = selected ? recordByTeacher.get(String(selected._id)) : null;

  const canAct = (rec) =>
    !(
      !rec ||
      processingId === rec._id ||
      rec.payoutStatus === "Paid" ||
      rec.payoutStatus === "Processing"
    );

  return (
    <div className="container-xxl py-4">
      <div className="d-flex flex-column flex-lg-row align-items-lg-center justify-content-between gap-3 mb-3">
        <div>
          <h3 className="mb-1 fw-bold text-primary">Teacher Salary Record</h3>
          <div className="text-muted">Select a teacher, then pay via Razorpay (test) or manual.</div>
        </div>
        <div className="d-flex align-items-center gap-2">
          <button
            className="btn btn-outline-primary"
            onClick={loadRecords}
            disabled={loading}
          >
            {loading ? "Refreshing..." : "Refresh"}
          </button>
          <button
            className="btn btn-primary"
            onClick={() => selected && handleCreateRecord(selected)}
            disabled={
              !selected ||
              processingId === selected?._id ||
              !!selectedRecord
            }
          >
            {processingId === selected?._id ? "Creating..." : "Create Salary Record"}
          </button>
        </div>
      </div>

      <div className="card border-0 shadow-sm mb-3">
        <div className="card-body d-flex flex-column flex-lg-row gap-2 align-items-lg-center justify-content-between">
          <div className="d-flex gap-2 flex-wrap">
            <div className="input-group" style={{ minWidth: 280 }}>
              <span className="input-group-text">🔎</span>
              <input
                className="form-control"
                placeholder="Search teacher / email..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <select
              className="form-select"
              style={{ width: 200 }}
              value={month}
              onChange={(e) => setMonth(e.target.value)}
            >
              {monthOptions.map((m) => (
                <option key={m} value={m}>
                  {m}
                </option>
              ))}
            </select>
          </div>

          <button
            className="btn btn-outline-secondary"
            onClick={handleGenerateSheet}
            disabled={generating || isMonthlyGenerated}
          >
            {isMonthlyGenerated ? "Monthly Sheet Generated" : generating ? "Generating..." : "Generate Monthly Sheet"}
          </button>
        </div>
      </div>

      <div className="row g-3">
        <div className="col-12 col-lg-5">
          <div className="card border-0 shadow-sm">
            <div className="card-body">
              <div className="fw-semibold mb-2">Teachers</div>
              <div className="list-group" style={{ maxHeight: 520, overflowY: "auto" }}>
                {filteredTeachers.map((t) => (
                  <button
                    key={t._id}
                    className={`list-group-item list-group-item-action ${
                      selected?._id === t._id ? "active" : ""
                    }`}
                    onClick={() => setSelected(t)}
                  >
                    <div className="d-flex justify-content-between align-items-center">
                      <div>
                        <div className="fw-semibold">{t.teacherName || "Teacher"}</div>
                        <div className="small">{t.email || "-"}</div>
                      </div>
                      <span className="badge text-bg-light">₹{t.salary || 0}</span>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>

        <div className="col-12 col-lg-7">
          {!selected ? (
            <div className="card border-0 shadow-sm h-100">
              <div className="card-body text-center py-5">
                <div className="fs-5 fw-semibold">Select a teacher</div>
                <div className="text-muted">Choose a teacher from the list to manage salary.</div>
              </div>
            </div>
          ) : (
            <div className="card border-0 shadow-sm h-100">
              <div className="card-body">
                <div className="d-flex justify-content-between align-items-start mb-3">
                  <div>
                    <h5 className="mb-1">{selected.teacherName || "Teacher"}</h5>
                    <div className="text-muted small">{selected.email || "-"}</div>
                  </div>
                  <span className="badge text-bg-light">Month: {month}</span>
                </div>

                <div className="row g-2 small">
                  <div className="col-6">
                    <div className="text-muted">Mobile</div>
                    <div className="fw-semibold">{selected.mobile || "-"}</div>
                  </div>
                  <div className="col-6">
                    <div className="text-muted">Amount</div>
                    <div className="fw-semibold">₹{selected.salary || 0}</div>
                  </div>
                  <div className="col-6">
                    <div className="text-muted">Payout Status</div>
                    <div className="fw-semibold">{selectedRecord?.payoutStatus || "No Record"}</div>
                  </div>
                  <div className="col-6">
                    <div className="text-muted">Mode</div>
                    <div className="fw-semibold">{selectedRecord?.payoutMode || "-"}</div>
                  </div>
                </div>

                <hr className="my-3" />

                {selectedRecord ? (
                  <div className="d-grid gap-2">
                    <button
                      className="btn btn-primary"
                      onClick={() => handlePayWithRazorpay(selectedRecord)}
                      disabled={!canAct(selectedRecord)}
                    >
                      {processingId === selectedRecord._id ? "Processing..." : "Pay Razorpay (Test)"}
                    </button>
                    <button
                      className="btn btn-outline-success"
                      onClick={() => handlePayNow(selectedRecord._id)}
                      disabled={!canAct(selectedRecord)}
                    >
                      Mark Paid (Manual)
                    </button>
                  </div>
                ) : (
                  <div className="alert alert-warning mb-0">
                    No record for {month}. Click “Create Salary Record” above.
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
