import React, { useEffect, useMemo, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import api from "../../../api/api";
import { toast } from "react-toastify";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";

export default function TeacherSalaryRecord() {
  const [teachers, setTeachers] = useState([]);
  const [records, setRecords] = useState([]);
  const [selected, setSelected] = useState(null);
  const [processingId, setProcessingId] = useState(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [search, setSearch] = useState("");
  const [month, setMonth] = useState(() => {
    const d = new Date();
    return d.toLocaleString("en-US", { month: "long" }) + " " + d.getFullYear();
  });
  const location = useLocation();
  const navigate = useNavigate();
  const initialTeacherId = location?.state?.teacherId || null;
  const autoGeneratedRef = useRef(false);
  const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
  ];
  
  const monthOptions = useMemo(() => {
    const currentYear = new Date().getFullYear();
    const years = [2025, currentYear];
    const uniqueYears = Array.from(new Set(years));
    return uniqueYears.flatMap((y) => months.map((m) => `${m} ${y}`));
  }, []);

  useEffect(() => {
    loadTeachers();
  }, []);

  useEffect(() => {
    loadRecords();
  }, [month]);

  const loadTeachers = async () => {
    try {
      const res = await api.get("/api/teacher-salary/teachers");
      setTeachers(res.data || []);
    } catch (err) {
      console.error("Error loading teachers:", err);
      toast.error("Failed to load teachers.");
    }
  };

  useEffect(() => {
    if (!initialTeacherId || teachers.length === 0) return;
    const found = teachers.find((t) => String(t._id) === String(initialTeacherId));
    if (found) setSelected(found);
  }, [initialTeacherId, teachers]);

  const loadRecords = async () => {
    try {
      setLoading(true);
      const res = await api.get("/api/teacher-salary/all");
      setRecords(res.data || []);
    } catch (err) {
      console.error("Error loading salary records:", err);
      toast.error("Failed to load salary records.");
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateSheet = async () => {
    if (!month) return;
    setGenerating(true);
    try {
      await api.post("/api/teacher-salary/monthly-sheet", { month });
      toast.success("Monthly sheet generated.");
      await loadRecords();
    } catch (err) {
      console.error("Error generating sheet:", err);
      toast.error("Failed to generate monthly sheet.");
    } finally {
      setGenerating(false);
    }
  };

  const handlePayNow = async (salaryId) => {
    if (!salaryId) return;
    setProcessingId(salaryId);
    try {
      await api.post(`/api/teacher-salary/payout/${salaryId}`);
      await loadRecords();
      toast.success("Payout processed.");
    } catch (err) {
      console.error("Error initiating payout:", err);
      toast.error("Failed to process payout.");
    } finally {
      setProcessingId(null);
    }
  };

  const handlePayWithRazorpay = async (record) => {
    if (!record?._id) return;
    if (!window.Razorpay) {
      toast.error("Razorpay SDK not loaded.");
      return;
    }
    setProcessingId(record._id);
    try {
      const res = await api.post(`/api/teacher-salary/razorpay/order/${record._id}`);
      if (res.data?.salary?.payoutStatus === "Paid") {
        toast.info("Payout already completed.");
        return;
      }

      const order = res.data?.order;
      const keyId = res.data?.keyId;
      if (!order?.id || !keyId) {
        toast.error("Failed to create Razorpay order.");
        return;
      }

      const options = {
        key: keyId,
        amount: order.amount,
        currency: order.currency,
        name: "SchoolY",
        description: `Salary payout - ${record.month}`,
        order_id: order.id,
        handler: async (response) => {
          try {
            await api.post("/api/teacher-salary/razorpay/verify", {
              salaryId: record._id,
              ...response,
            });
            toast.success("Payment successful.");
            await loadRecords();
          } catch (verifyErr) {
            console.error("Error verifying payment:", verifyErr);
            toast.error("Payment verification failed.");
          } finally {
            setProcessingId(null);
          }
        },
        modal: {
          ondismiss: () => {
            toast.info("Payment cancelled.");
            setProcessingId(null);
          },
        },
        prefill: {
          name: record.teacher?.teacherName || "Teacher",
          email: record.teacher?.email || "",
        },
        notes: {
          salaryId: record._id,
          month: record.month,
        },
        theme: { color: "#4f46e5" }, // Updated to match SchoolY primary color
      };

      const rzp = new window.Razorpay(options);
      rzp.on("payment.failed", (resp) => {
        console.error("Razorpay payment failed:", resp);
        toast.error(resp?.error?.description || "Payment failed.");
        setProcessingId(null);
      });
      rzp.open();
    } catch (err) {
      console.error("Error creating Razorpay order:", err);
      toast.error("Failed to initiate Razorpay payment.");
      setProcessingId(null);
    }
  };

  const handleCreateRecord = async (teacher) => {
    try {
      setProcessingId(teacher._id);
      const payload = {
        teacher: teacher._id,
        month,
        paidAmount: teacher.salary || 0,
        status: "Pending",
      };
      const res = await api.post("/api/teacher-salary/pay", payload);
      toast.success("Salary record created.");
      await loadRecords();
      return res.data?.salary || null;
    } catch (err) {
      if (err?.response?.status === 409) {
        toast.info("Salary record already exists.");
        await loadRecords();
        return err?.response?.data?.record || null;
      }
      console.error("Error creating salary record:", err);
      toast.error("Failed to create salary record.");
      return null;
    } finally {
      setProcessingId(null);
    }
  };

  const recordByTeacher = useMemo(() => {
    const map = new Map();
    (records || [])
      .filter((r) => r?.month === month)
      .forEach((r) => {
        if (r?.teacher?._id) map.set(String(r.teacher._id), r);
      });
    return map;
  }, [records, month]);

  const monthlyRecordCount = useMemo(() => {
    return (records || []).filter((r) => r?.month === month).length;
  }, [records, month]);

  const isMonthlyGenerated = useMemo(() => {
    if (!teachers.length) return false;
    return monthlyRecordCount >= teachers.length;
  }, [monthlyRecordCount, teachers.length]);

  const filteredTeachers = useMemo(() => {
    const q = search.trim().toLowerCase();
    return (teachers || []).filter((t) => {
      if (!q) return true;
      const name = (t?.teacherName || "").toLowerCase();
      const email = (t?.email || "").toLowerCase();
      return name.includes(q) || email.includes(q);
    });
  }, [teachers, search]);

  useEffect(() => {
    if (autoGeneratedRef.current) return;
    if (loading) return;
    if (!teachers.length) return;
    if (isMonthlyGenerated) return;
    autoGeneratedRef.current = true;
    handleGenerateSheet();
  }, [loading, teachers.length, isMonthlyGenerated]);

  const selectedRecord = selected ? recordByTeacher.get(String(selected._id)) : null;

  const canAct = (rec) =>
    !(
      !rec ||
      processingId === rec._id ||
      rec.payoutStatus === "Paid" ||
      rec.payoutStatus === "Processing"
    );

  // Helper for status badges
  const getStatusBadge = (status) => {
    switch(status) {
      case "Paid": return "bg-success text-white border-success";
      case "Processing": return "bg-info text-white border-info";
      case "Pending": return "bg-warning text-dark border-warning";
      case "Failed": return "bg-danger text-white border-danger";
      default: return "bg-secondary text-white border-secondary";
    }
  };

  return (
    <div className="container-fluid py-4 min-vh-100" style={{ backgroundColor: "#f8fafc", fontFamily: "'Inter', sans-serif" }}>
      
      {/* Premium Custom CSS */}
      <style>{`
        .premium-card { background: #ffffff; border: 1px solid #e2e8f0; border-radius: 16px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.02); transition: all 0.2s; }
        
        .input-premium { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 10px 16px; transition: all 0.2s; font-weight: 500; color: #0f172a; }
        .input-premium:focus { border-color: #4f46e5; box-shadow: 0 0 0 4px rgba(79, 70, 229, 0.1); background: #ffffff; outline: none; }
        
        .btn-brand { background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%); border: none; color: white; transition: all 0.2s; font-weight: 600; }
        .btn-brand:hover { transform: translateY(-1px); box-shadow: 0 6px 16px rgba(79, 70, 229, 0.3); color: white; }
        .btn-brand:disabled { opacity: 0.7; transform: none; box-shadow: none; cursor: not-allowed; }
        
        .teacher-list-item { transition: all 0.2s ease; border: 1px solid transparent; border-bottom: 1px solid #f1f5f9; cursor: pointer; padding: 16px; background: #ffffff; }
        .teacher-list-item:hover { background: #f8fafc; }
        .teacher-list-item.active { background: #eef2ff; border-color: #c7d2fe; border-radius: 12px; border-bottom: 1px solid #c7d2fe; box-shadow: 0 4px 6px -1px rgba(79,70,229,0.05); }
        
        .avatar-circle { width: 44px; height: 44px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 1.1rem; }
        
        .custom-scroll::-webkit-scrollbar { width: 6px; }
        .custom-scroll::-webkit-scrollbar-thumb { background-color: #cbd5e1; border-radius: 10px; }
        
        .animate-fade-in { animation: fadeIn 0.3s ease-out forwards; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
      `}</style>

      <div className="container" style={{ maxWidth: "1300px" }}>
        
        {/* Premium Header Card */}
        <div 
          className="rounded-4 overflow-hidden mb-4 shadow-sm border-0 position-relative p-4 p-md-5"
          style={{ background: "linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)" }}
        >
          <div style={{ position: 'absolute', top: '-50%', right: '-5%', width: '300px', height: '300px', background: 'rgba(255,255,255,0.05)', borderRadius: '50%' }}></div>
          <div className="position-relative z-1 d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-4">
            <div>
              <span className="badge px-3 py-2 rounded-pill fw-semibold mb-3" style={{ background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(10px)', border: '1px solid rgba(255,255,255,0.3)', color: 'white' }}>
                <i className="bi bi-wallet2 me-1"></i> Financial Administration
              </span>
              <h2 className="display-6 fw-bolder text-white mb-1" style={{ letterSpacing: '-1px' }}>Teacher Salary Records</h2>
              <p className="text-white opacity-75 fw-medium mb-0">Process monthly payroll manually or securely via Razorpay.</p>
            </div>
            
            <button
              className="btn bg-white text-primary rounded-pill px-4 py-3 fw-bold shadow-sm transition-all text-nowrap"
              onClick={handleGenerateSheet}
              disabled={generating || isMonthlyGenerated}
            >
              {generating ? (
                <><span className="spinner-border spinner-border-sm me-2"></span>Generating...</>
              ) : isMonthlyGenerated ? (
                <><i className="bi bi-check-circle-fill me-2 text-success"></i> Sheet Generated</>
              ) : (
                <><i className="bi bi-file-earmark-plus-fill me-2"></i> Generate Monthly Sheet</>
              )}
            </button>
          </div>
        </div>

        {/* Filter Bar */}
        <div className="premium-card p-3 mb-4">
          <div className="row g-3 align-items-center">
            <div className="col-12 col-md-5 col-lg-6">
              <div className="position-relative">
                <i className="bi bi-search position-absolute text-muted" style={{ top: '50%', transform: 'translateY(-50%)', left: '16px' }}></i>
                <input
                  type="text"
                  className="form-control input-premium w-100"
                  style={{ paddingLeft: '44px' }}
                  placeholder="Search teacher by name or email..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                />
              </div>
            </div>
            <div className="col-12 col-md-4 col-lg-4">
              <div className="d-flex align-items-center bg-light border rounded-3 px-3">
                <i className="bi bi-calendar-month text-muted me-2"></i>
                <select
                  className="form-select border-0 bg-transparent shadow-none fw-semibold text-dark py-2 px-1"
                  value={month}
                  onChange={(e) => setMonth(e.target.value)}
                >
                  {monthOptions.map((m) => (
                    <option key={m} value={m}>{m}</option>
                  ))}
                </select>
              </div>
            </div>
            <div className="col-12 col-md-3 col-lg-2">
              <button
                className="btn btn-light border w-100 fw-bold text-muted py-2 rounded-3"
                onClick={loadRecords}
                disabled={loading}
              >
                {loading ? <span className="spinner-border spinner-border-sm"></span> : <><i className="bi bi-arrow-clockwise me-1"></i> Refresh</>}
              </button>
            </div>
          </div>
        </div>

        {/* Main Content Layout */}
        <div className="row g-4">
          
          {/* Left Column: Teacher List */}
          <div className="col-12 col-lg-5">
            <div className="premium-card h-100 d-flex flex-column overflow-hidden">
              <div className="p-4 border-bottom bg-light bg-opacity-50" style={{ borderColor: '#f1f5f9' }}>
                <h6 className="fw-bolder text-dark mb-0 d-flex align-items-center">
                  <i className="bi bi-people-fill text-primary me-2"></i> Faculty Directory
                </h6>
              </div>
              <div className="flex-grow-1 custom-scroll" style={{ maxHeight: "600px", overflowY: "auto" }}>
                {filteredTeachers.length === 0 ? (
                  <div className="text-center py-5 text-muted fw-medium">
                    <i className="bi bi-search fs-2 d-block mb-2 opacity-50"></i>
                    No teachers found.
                  </div>
                ) : (
                  filteredTeachers.map((t) => {
                    const isSelected = selected?._id === t._id;
                    return (
                      <div
                        key={t._id}
                        className={`teacher-list-item d-flex justify-content-between align-items-center ${isSelected ? "active" : ""}`}
                        onClick={() => setSelected(t)}
                      >
                        <div className="d-flex align-items-center gap-3">
                          <div className={`avatar-circle shadow-sm border ${isSelected ? "bg-white text-primary border-primary" : "bg-light text-muted border-secondary border-opacity-25"}`}>
                            {t.teacherName?.charAt(0).toUpperCase() || "T"}
                          </div>
                          <div>
                            <div className={`fw-bolder mb-1 lh-sm ${isSelected ? "text-primary" : "text-dark"}`}>
                              {t.teacherName || "Unknown Teacher"}
                            </div>
                            <div className="small text-muted fw-medium" style={{ fontSize: '0.75rem' }}>
                              {t.email || "No Email"}
                            </div>
                          </div>
                        </div>
                        <span className={`badge rounded-pill px-3 py-2 fw-bold shadow-sm ${isSelected ? "bg-primary text-white" : "bg-light text-dark border"}`}>
                          ₹{t.salary?.toLocaleString() || 0}
                        </span>
                      </div>
                    );
                  })
                )}
              </div>
            </div>
          </div>

          {/* Right Column: Payment Console */}
          <div className="col-12 col-lg-7">
            {!selected ? (
              <div className="premium-card h-100 d-flex flex-column align-items-center justify-content-center py-5 text-muted bg-light bg-opacity-50">
                <div className="rounded-circle bg-white shadow-sm d-flex align-items-center justify-content-center mb-4" style={{ width: 80, height: 80 }}>
                  <i className="bi bi-person-bounding-box fs-1 opacity-50"></i>
                </div>
                <h5 className="fw-bolder text-dark mb-2">Select a Faculty Member</h5>
                <p className="fw-medium mb-0">Choose a teacher from the directory to manage their payroll.</p>
              </div>
            ) : (
              <div className="premium-card h-100 d-flex flex-column animate-fade-in overflow-hidden">
                
                {/* Profile Header */}
                <div className="p-4 p-md-5 border-bottom position-relative" style={{ backgroundColor: '#f8fafc', borderColor: '#e2e8f0' }}>
                  <div className="d-flex justify-content-between align-items-start mb-4">
                    <div className="d-flex align-items-center gap-3">
                      <div className="avatar-circle bg-primary text-white shadow fw-bolder fs-3" style={{ width: 64, height: 64 }}>
                        {selected.teacherName?.charAt(0).toUpperCase()}
                      </div>
                      <div>
                        <h4 className="fw-bolder text-dark mb-1">{selected.teacherName}</h4>
                        <div className="badge bg-white text-muted border px-3 py-1 rounded-pill fw-semibold shadow-sm">
                          <i className="bi bi-calendar2-check text-primary me-1"></i> {month}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="row g-3 bg-white p-3 rounded-4 border shadow-sm">
                    <div className="col-6 col-md-3 border-end-md" style={{ borderColor: '#f1f5f9' }}>
                      <div className="text-muted small fw-bold text-uppercase mb-1" style={{ fontSize: '0.65rem', letterSpacing: '0.5px' }}>Contact</div>
                      <div className="fw-bolder text-dark text-truncate" style={{ fontSize: '0.9rem' }}>{selected.mobile || "N/A"}</div>
                    </div>
                    <div className="col-6 col-md-3 border-end-md" style={{ borderColor: '#f1f5f9' }}>
                      <div className="text-muted small fw-bold text-uppercase mb-1" style={{ fontSize: '0.65rem', letterSpacing: '0.5px' }}>Base Salary</div>
                      <div className="fw-bolder text-dark" style={{ fontSize: '0.9rem' }}>₹{selected.salary?.toLocaleString() || 0}</div>
                    </div>
                    <div className="col-6 col-md-3 border-end-md" style={{ borderColor: '#f1f5f9' }}>
                      <div className="text-muted small fw-bold text-uppercase mb-1" style={{ fontSize: '0.65rem', letterSpacing: '0.5px' }}>Status</div>
                      <span className={`badge rounded-pill px-2 border ${getStatusBadge(selectedRecord?.payoutStatus || "Pending")}`}>
                        {selectedRecord?.payoutStatus || "No Record"}
                      </span>
                    </div>
                    <div className="col-6 col-md-3">
                      <div className="text-muted small fw-bold text-uppercase mb-1" style={{ fontSize: '0.65rem', letterSpacing: '0.5px' }}>Payout Mode</div>
                      <div className="fw-bolder text-dark" style={{ fontSize: '0.9rem' }}>{selectedRecord?.payoutMode || "—"}</div>
                    </div>
                  </div>
                </div>

                {/* Action Console */}
                <div className="p-4 p-md-5 flex-grow-1 bg-white d-flex flex-column justify-content-center">
                  {selectedRecord ? (
                    <div className="text-center">
                      <div className="mb-4">
                        <i className={`bi ${selectedRecord.payoutStatus === "Paid" ? "bi-check-circle-fill text-success" : "bi-wallet2 text-primary"} display-1 opacity-75`}></i>
                      </div>
                      <h5 className="fw-bolder text-dark mb-2">
                        {selectedRecord.payoutStatus === "Paid" ? "Salary Settled" : "Process Salary Payment"}
                      </h5>
                      <p className="text-muted fw-medium mb-4 mx-auto" style={{ maxWidth: '400px' }}>
                        {selectedRecord.payoutStatus === "Paid" 
                          ? `The salary of ₹${selected.salary} for ${month} has been successfully processed.`
                          : `Initiate the payout of ₹${selected.salary} for the month of ${month}.`}
                      </p>
                      
                      <div className="d-flex flex-column flex-sm-row justify-content-center gap-3">
                        <button
                          className="btn btn-brand btn-lg rounded-pill px-5 shadow-sm fw-bold"
                          onClick={() => handlePayWithRazorpay(selectedRecord)}
                          disabled={!canAct(selectedRecord)}
                        >
                          {processingId === selectedRecord._id ? (
                            <><span className="spinner-border spinner-border-sm me-2"></span>Connecting...</>
                          ) : (
                            <><i className="bi bi-credit-card-fill me-2"></i> Pay via Razorpay</>
                          )}
                        </button>
                        <button
                          className="btn bg-light border text-success btn-lg rounded-pill px-4 fw-bold shadow-sm transition-all"
                          onClick={() => handlePayNow(selectedRecord._id)}
                          disabled={!canAct(selectedRecord)}
                          style={{ hoverBackgroundColor: '#f0fdf4' }}
                        >
                          <i className="bi bi-check2-all me-2"></i> Mark as Paid
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-4">
                      <div className="rounded-circle bg-warning bg-opacity-10 d-inline-flex align-items-center justify-content-center mb-4" style={{ width: 80, height: 80 }}>
                        <i className="bi bi-exclamation-triangle-fill text-warning fs-1"></i>
                      </div>
                      <h5 className="fw-bolder text-dark mb-2">No Record Found</h5>
                      <p className="text-muted fw-medium mb-4 mx-auto" style={{ maxWidth: '400px' }}>
                        A salary record for <strong>{month}</strong> has not been generated for this teacher yet.
                      </p>
                      <button
                        className="btn btn-brand btn-lg rounded-pill px-5 shadow-sm fw-bold"
                        onClick={() => handleCreateRecord(selected)}
                        disabled={processingId === selected._id}
                      >
                        {processingId === selected._id ? (
                          <><span className="spinner-border spinner-border-sm me-2"></span>Creating...</>
                        ) : (
                          <><i className="bi bi-file-earmark-plus-fill me-2"></i> Create Salary Record</>
                        )}
                      </button>
                    </div>
                  )}
                </div>
              </div>
          )}
        </div>
      </div>
    </div>
    </div>
  );
}